### ISSUE TITLE
map scrolling east west

### ISSUE THREAD

**Issue by nthieberger** [marcolarosa/pdsc-olac-datasource#12]
Can the map be like the one in the 50words project, allowing continuous scrolling east-west so the Pacific is not the edge of the world?

**Comment by marcolarosa** [comment]
I think this in the wrong repo - does this apply to the olacvis? (http://language-archives.services/olacvis/#/) If so, then the answer is unfortunately I can't. That app is so old I can't rebuild it without putting in significant effort to update all dependencies. From memory we discussed this a while back and both came to the conclusion that it wasn't worth the effort. Has that changed?

**Comment by nthieberger** [comment]
It is in the right repo. No need to do anything if it is going to be a
major effort.

**Comment by marcolarosa** [comment]
Sorry - you're right. I have the repo's confused!
