### ISSUE TITLE
no links from language resources

### ISSUE THREAD

**Issue by nthieberger** [marcolarosa/pdsc-olac-datasource#13]
Having clicked on a language, then selected 'more information' , then one of the headings (e.g. 'primary texts'), the links do not go anywhere, and a blank popup appears. (Firefox)

**Comment by marcolarosa** [comment]
These issues should be logged in: https://github.com/marcolarosa/pdsc-olac-visualisation but then I can't built that app anymore so I can't fix any issues with it. If you really want to keep using it we should redo it in modern code and tools.
